import "./globals.css";
import { Raleway, Roboto, Inter } from "next/font/google";

// components
import Navbar from "./components/Navbar";

const raleway = Raleway({ subsets: ["latin"] });
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Muhammad Rizqi Az Zayyad",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  );
}
